name: Barman Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'barman release (ex: release/2.18)'
        required: true

jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['didiermichel/barman-packaging']
    name: Trigger barman packaging update
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          # Personal access token to trigger the other pipelines
          token: ${{ secrets.DELIVER_REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: dispatch_release
          client-payload: '{"release_name": "${{ github.event.inputs.release }}"}'
