name: Barman Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'barman release (ex: 2.18)'
        required: true

jobs:

  set_version:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/didiermichel/pandoc:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DELIVER_REPO_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
#          ${GITHUB_WORKSPACE}/scripts/ci-set-version.sh 2.18
          ${GITHUB_WORKSPACE}/scripts/ci-set-version.sh ${{ github.event.inputs.release }}
      - run: git -C ${GITHUB_WORKSPACE} status



#  dispatch:
#    needs: release
#    strategy:
#      matrix:
#        repo: ['didiermichel/barman-packaging']
#    name: Trigger barman packaging update
#    runs-on: ubuntu-latest
#    steps:
#      - name: Repository dispatch
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          # Personal access token to trigger the other pipelines
#          token: ${{ secrets.DELIVER_REPO_ACCESS_TOKEN }}
#          repository: ${{ matrix.repo }}
#          event-type: dispatch_release
#          client-payload: '{"release_name": "release/${{ github.event.inputs.release }}"}'
